# 构建docker-compose项目
# docker compose --log-level INFO up -- build
# docker compose --log-level INFO up -d --build

version: '3'
services:
  terwer-nginx:
    image: terwer/nginx:1.15.9
    container_name: terwer-nginx
    build:
      context: ./terwer-nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./terwer-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./terwer-nginx/data/nginx/log:/var/log/nginx
      - ./terwer-nginx/ssl/v4.pem:/etc/ssl/v4.pem
      - ./terwer-nginx/ssl/v4.key:/etc/ssl/v4.key
    restart: "no"
  siyuan-nginx:
    image: siyuan/nginx:1.15.9
    container_name: siyuan-nginx
    build:
      context: ./siyuan-nginx
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./siyuan-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./siyuan-nginx/data/nginx/log:/var/log/nginx
      - ./siyuan-nginx/ssl/siyuan.pem:/etc/ssl/siyuan.pem
      - ./siyuan-nginx/ssl/siyuan.key:/etc/ssl/siyuan.key
    restart: "no"