# 构建docker-compose项目
# docker compose --log-level INFO up -- build
# docker compose --log-level INFO up -d --build

version: '3'
services:
  mk-nginx:
    image: mk/nginx:1.15.9
    container_name: mk-nginx
    build:
      context: ./mk-nginx
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - ./mk-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./mk-nginx/data/nginx/log:/var/log/nginx
      - ./mk-nginx/data/nginx/html:/usr/local/nginx/html
    restart: "no"