# 构建docker-compose项目
# docker compose --log-level INFO up -- build
# docker compose --log-level INFO up -d --build

version: '3'
services:
  mk-nginx:
    image: vuepress/nginx:1.15.9
    container_name: vuepress-nginx
    build:
      context: ./vuepress-nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./vuepress-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./vuepress-nginx/data/nginx/log:/var/log/nginx
      # - ./vuepress-nginx/data/nginx/html:/usr/local/nginx/html
      - /Users/terwer/Documents/mydocs/terwer.github.io/docs/.vuepress/dist:/usr/local/nginx/html
    restart: "no"